- name: add index.html
  file:
    path: /var/www/html/index.html
    state: touch
    owner: admin1
    group: admin1
    mode: '0644'

- name: populate text in index.html
  lineinfile:
    path: /var/www/html/index.html
    line: hello world!
